### ISSUE TITLE
Multiple instantaneous connection handling

### ISSUE THREAD

**Issue by MikeDev101** [MikeDev101/cloudlink#1]
Currently, trying to acquire data instantaneously from the client to the server is very flawed, and when the client attempts to request multiple things at once, it corrupts the returns and some packets never receive correctly.

As per [20e9fc5](https://github.com/MikeDev101/cloudlink/commit/20e9fc57a0230dea55ba7a711fb5f993d90a0517), I have implemented a temporary placeholder script in the client, but this is also buggy. I will be taking a look at improving the server and the client code.

**Comment by KingdomPy** [comment]
I tried an extension like this as well https://github.com/KingdomPy/scratch_websockets/.
What i did was have my python server send any messages it receives straight to scratch. When the data was received in scratch it would be added to a stack that would be emptied whenever it was checked for messages. I don't know if this helps but good luck.

**Comment by MikeDev101** [comment]
Issue has been fixed as of 0.1.9/0.1.7 (client version/server version). This topic will be closed.
