### ISSUE TITLE
Can't set JSON in Global Variables

### ISSUE THREAD

**Issue by sm4rd4** [MikeDev101/cloudlink#102]
Whenever I try to set a JSON value in a global variable, it always gets changed to "[object Object]".

Is there a way to fix this?

**Comment by MikeDev101** [comment]
Hey there!

Before I continue, what version of the CL protocol (CL3, CL4) and what version of the server are you using? (Example: 0.1.9.3 is latest at this time)

**Comment by sm4rd4** [comment]
Ah, it seems my version is outdated. I'm running version 0.1.9.1

I'll update and see if that fixes it. Thanks!

**Comment by sm4rd4** [comment]
I can't seem to find 0.1.9.3, but I have updated to 0.1.9.2 and I'm still getting the same issue.

**Comment by showierdata9978** [comment]
if your running a server, the best thing to do is clone the repo, and edit the example files

**Comment by MikeDev101** [comment]
> I can't seem to find 0.1.9.3, but I have updated to 0.1.9.2 and I'm still getting the same issue.

Judging by "object Object", you are using an older extension version. Use the latest version in this repository before continuing.

**Comment by sm4rd4** [comment]
Apologies if I sound like a complete idiot, but where can I get the latest version of both the extension and the server?
(p.s i also tried using the unsandboxed version of the extension and still no dice)

**Comment by MikeDev101** [comment]
> Apologies if I sound like a complete idiot, but where can I get the latest version of both the extension and the server? (p.s i also tried using the unsandboxed version of the extension and still no dice)

https://github.com/MikeDev101/cloudlink/archive/refs/heads/master.zip

**Comment by MikeDev101** [comment]
![image](https://github.com/MikeDev101/cloudlink/assets/12957745/ca7c0bde-737c-4d84-9e50-b4f2ad489273)

seems like a client-level bug that also appears with global/private variables

**Comment by MikeDev101** [comment]
Python client/server 0.2.0 has been released. I need to confirm if this issue still exists with the new codebase.

**Comment by MikeDev101** [comment]
Extension should be fixed. https://github.com/MikeDev101/cloudlink/commit/6b9cb2f5a35aff34c330532d8ee2aed48277b2f2
