### ISSUE TITLE
ImportError: cannot import name 'CloudLink' from 'cloudlink' on server start

### ISSUE THREAD

**Issue by tapiov** [MikeDev101/cloudlink#104]
Hi, I am not very fluent in Python unfortunately. I used the instructions here

https://hackmd.io/G9q1kPqvQT6NrPobjjxSgg?view#Python-ServerClient-Quickstart-Guide

Did:
python3 -m pip install cloudlink

and pip list shows 
cloudlink              0.1.9.1

I used start up script like 
from cloudlink import CloudLink
cl = CloudLink()
cl.server()

which fails with 
ImportError: cannot import name 'CloudLink' from 'cloudlink'

What am I doing wrong here?

**Comment by MikeDev101** [comment]
Hi there, please directly download the library from this repo. I haven't maintained the pypi version in a while. https://github.com/MikeDev101/cloudlink/archive/refs/heads/master.zip

**Comment by tapiov** [comment]
Thanks for quick reply. I cloned the repo with git clone. It's next to start.py (post above). Now I get
python3 start.py

Traceback (most recent call last):
  File "/home/tapio/Projects/Turbowarp/start.py", line 1, in <module>
    from cloudlink import CloudLink
ImportError: cannot import name 'CloudLink' from 'cloudlink' (unknown location)

**Comment by tapiov** [comment]
Ok, read your answer to the end :)
 
Updated the start.py to 

from cloudlink import cloudlink

# Somewhere before you start the server, you define custom methods / events

if __name__ == "__main__":
    cl = cloudlink() # Instanciate the parent cloudlink object
    server = cl.server(logs=True) # Initialize a new server object

    # Do configuration here

    server.run(
        ip = "localhost", # Defaults to 127.0.0.1, use 0.0.0.0 to host on all interfaces
        port = 3000 # Defaults to port 3000
    )
# server.run() is blocking,
# no further code will execute unless a CTRL+C, SIGTERM, or SIGKILL is detected. 

Now get 

python3 start.py
Traceback (most recent call last):
  File "/home/tapio/Projects/Turbowarp/start.py", line 6, in <module>
    cl = cloudlink() # Instanciate the parent cloudlink object
TypeError: 'module' object is not callable

**Comment by showierdata9978** [comment]
its `cl = cloudlink,Cloudlink()`

**Comment by tapiov** [comment]
Yes, thanks!

```
cl = cloudlink.cloudlink() 
```
works!! Thanks!
