### ISSUE TITLE
"Nonetype has no attributes "users" " while send_packet_multicast

### ISSUE THREAD

**Issue by aGoatdev** [MikeDev101/cloudlink#112]
has i saw the problem, it appear that in this server's method, your define the args room_id to None, but there is no rooms with the id None, so i think you should replace it with "default". that worked for me.

**Comment by aGoatdev** [comment]
> that worked for me.
i just put "room_id" to default.

**Comment by MikeDev101** [comment]
closing since stale. not sure how to reproduce it since aGoatdev's issue is vague.
