### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by TheShovel** [MikeDev101/cloudlink#113]
I want to host my own instance, so I put it on my Raspberry Pi4, port forwarded, and then tried to connect. Every time I connect I get `connection failed (400 bad request)` in the logs on my Pi. What could be causing this?

**Comment by showierdata9978** [comment]
SSL most likely

**Comment by TheShovel** [comment]
How could I add SSL?

**Comment by MikeDev101** [comment]
If you are using a copy of the server from the - 0.2.0 branch, you may check this repo's wiki page to see how to enable SSL support.

Otherwise, you must use a reverse proxy or tunneling service like cloudflare tunnels or ngrok.

**Comment by TheShovel** [comment]
Both Ngrok and Cloudflare tunnels randomize the adrress. I want it to be static.

**Comment by MikeDev101** [comment]
I suggest upgrading to the 0.2.0 branch instead.

**Comment by showierdata9978** [comment]
> Both Ngrok and Cloudflare tunnels randomize the adrress. I need it to be static.

You need a domain for CF tunnels to be static

**Comment by TheShovel** [comment]
> I suggest upgrading to the 0.2.0 branch instead. I was intending to EOL any older variant by now but I haven't got the chance.
I get this error when I try to do that...
![Uploading Screenshot_20230604_214907_VNC Viewer.png…]()

**Comment by TheShovel** [comment]
![Screenshot_20230604_214907_VNC Viewer](https://github.com/MikeDev101/cloudlink/assets/68913917/a7192b1a-955c-4aa9-9aa2-44e132f6ad19)

**Comment by showierdata9978** [comment]
you need to install dependencys

**Comment by MikeDev101** [comment]
> ![Screenshot_20230604_214907_VNC Viewer](https://github.com/MikeDev101/cloudlink/assets/68913917/a7192b1a-955c-4aa9-9aa2-44e132f6ad19)
> 

You need to install required libraries. Just use

`pip install -r requirements.txt`

(May be different depending upon platform)

**Comment by TheShovel** [comment]
Ah, I forgot to do that. I thought it used the same dependencies. Thanks for all the help! I sadly don't think that using a tunnel is the best idea for me, so I'm going to try and find a cloud host for it.
