### ISSUE TITLE
Randomly getting disconnected

### ISSUE THREAD

**Issue by derpygamer2142** [MikeDev101/cloudlink#114]
I am getting disconnected constantly, whereas before I was almost never getting disconnected. When it does happen, it always says that it the lost connection variable is true.

**Comment by MikeDev101** [comment]
Hey there, what server are you connecting to?

Some servers require you to send

`{"cmd": "ping"}`

As a keepalive, since they have a timeout period.

**Comment by derpygamer2142** [comment]
The issue seems to have been resolved, but I was trying to connect to server 2. I'll let you know if it returns.

**Comment by tnix100** [comment]
> The issue seems to have been resolved, but I was trying to connect to server 2. I'll let you know if it returns.

Server 2 is hosted on Replit, which is known to be unreliable.

**Comment by showierdata9978** [comment]
Server 2 is also no longer worked on.

**Comment by derpygamer2142** [comment]
> Server 2 is also no longer worked on.

so does that mean it will shut down, it'll be outdated, or i'll be the only one using it?

**Comment by showierdata9978** [comment]
it will be outdated

**Comment by derpygamer2142** [comment]
ok got it, i'll switch to server 1 because that has worked in the past

**Comment by MikeDev101** [comment]
Should no longer be an issue with 0.2.0.
