### ISSUE TITLE
Cant link to room

### ISSUE THREAD

**Issue by lolpng944** [MikeDev101/cloudlink#117]
I really need the room function cause my game is multiplayer with different matches
But i cant because the username function is required to create a room but its disabled (saw it in the logs)
Is there any other way i can make a room and why got the username function disabled

**Comment by showierdata9978** [comment]
Your using server 2, that uses a custom protocol extension.

**Comment by lolpng944** [comment]
So what of the code must i install to only use server 1?

**Comment by showierdata9978** [comment]
`connect to server (1)`

**Comment by lolpng944** [comment]
thanks for the help. it works now

**Comment by lolpng944** [comment]
i use my own server but it always seems to use the custom protocol so where can i find the source code without the this

**Comment by lolpng944** [comment]
how can i use this in my own server?

**Comment by tnix100** [comment]
> i use my own server but it always seems to use the custom protocol so where can i find the source code without this

Where are you currently getting the source code from?

**Comment by lolpng944** [comment]
rhis repository the whole code

**Comment by tnix100** [comment]
> this repository, the whole code

This repo doesn't include the custom protocol stuff that server 2 uses. Are you getting the error about setid being disabled on others servers?

**Comment by lolpng944** [comment]
yes i cloned this repository on my replit server and got the error in the console

**Comment by tnix100** [comment]
> no but i cloned this repository on my replit server and got the error in the console

Can you send me a link to the repl?

**Comment by lolpng944** [comment]
> > no but i cloned this repository on my replit server and got the error in the console
> 
> Can you send me a link to the repl?

cloudlink.zghghffgbfgfg.repl.co

**Comment by tnix100** [comment]
> 

Yeah this has custom codes that's used within server 2... this was definitely not cloned from this repo though because that code doesn't exist in this repo.

**Comment by tnix100** [comment]
It looks like your repl was cloned from @showierdata9978's repl which is server 2. Create a new repl and choose 'Import from GitHub'. Also make sure when importing you do `MikeDev101/cloudlink` for the repo you want to import from.
![image](https://github.com/MikeDev101/cloudlink/assets/61485190/09c617de-aed3-4f04-9068-29e8ae245cfe)

**Comment by lolpng944** [comment]
ok, thanks it works now
