### ISSUE TITLE
Please add documentation for the 3 types of data (Global, Private, and Direct)

### ISSUE THREAD

**Issue by StupidRepo** [MikeDev101/cloudlink#129]
I just spent 30 minutes figuring out why sending data to myself wasn't being registered, until I realised I should be using the Private type of data instead of direct in the "When I recieve new [data type] data" block.

**Comment by MikeDev101** [comment]
Hi there,

I apologize for the inconvenience. The wiki page is still under development, but there is documentation for the various message types you can use. It's a bit old but the fundamental concepts still apply: https://hackmd.io/@MikeDEV/SywNTBqRD
