### ISSUE TITLE
Send Var (var) with Data (val) does not work with a new line

### ISSUE THREAD

**Issue by DabDatBass** [MikeDev101/cloudlink#13]
In new line I mean https://scratch.mit.edu/projects/395084280/. This project shown is a hack of having a new line in Scratch, something you can't normally do. I wanted to use this for a project I was working on, but then after testing it with the Send Var blocks it loads the string but not anything after the new line. Please fix the bug :)

**Comment by MikeDev101** [comment]
Sorry, but it looks like this is a design flaw that would require a radical code rewrite. Packets are formatted using newline characters, and changing how packets are parsed would take too long to patch. Labeling this as a wontfix.
