### ISSUE TITLE
Errors in disk, coin, and account.

### ISSUE THREAD

**Issue by Ganheso** [MikeDev101/cloudlink#14]
Traceback (most recent call last):
  File "clouddisk.py", line 228, in <module>
    ws = websocket.WebSocketApp(IP, on_open = on_open, on_message = on_message, on_error = on_error, on_close = on_close)
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

Traceback (most recent call last):
  File "cloudcoin.py", line 134, in <module>
    ws = websocket.WebSocketApp(IP, on_open = on_open, on_message = on_message, on_error = on_error, on_close = on_close)
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

Traceback (most recent call last):
  File "cloudaccount.py", line 183, in <module>
    ws = websocket.WebSocketApp(IP, on_open = on_open, on_message = on_message, on_error = on_error, on_close = on_close)
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

**Comment by MikeDev101** [comment]
sometimes not having the correct WebSocket library causes this problem. You need to pip install WebSockets. https://websockets.readthedocs.io/en/stable/
