### ISSUE TITLE
Add password-based authentication for usernames to ensure true identity

### ISSUE THREAD

**Issue by VelocityDesign** [MikeDev101/cloudlink#19]
^ see title :)

**Comment by MikeDev101** [comment]
1. Currently working on implementing a feature similar to this called Trusted Access.
2. The feature was historically implemented over CloudAccount, which is due for porting to CLPv3

**Comment by VelocityDesign** [comment]
> 1. Currently working on implementing a feature similar to this called Trusted Access.
> 2. The feature was historically implemented over CloudAccount, which is due for porting to CLPv3

Got it!
