### ISSUE TITLE
server.py problems

### ISSUE THREAD

**Issue by UsernameNotAvalible** [MikeDev101/cloudlink#2]
server.py will not run, showing the following message:
` File "server.py", line 23
    async def client(websocket, path):
            ^
SyntaxError: invalid syntax
`

**Comment by UsernameNotAvalible** [comment]
i tried python 3, and now it complains about websockets not being a valid import

**Comment by MikeDev101** [comment]
Hi, what version of python are you running on? Windows? Linux? MacOS? You should be fine if you run 

`pip3 install websockets`

and execute the server.py file with

`python3 server.py`

**Comment by UsernameNotAvalible** [comment]
How do i get the pip command downloaded? it is not in the Linux repositories for me.

**Comment by MikeDev101** [comment]
Hm, looks like pip isn't installed, if that's what your trying to say. I would recommend taking a look here: https://pip.pypa.io/en/stable/installing/

**Comment by MikeDev101** [comment]
Closing this issue to to inactivity.
