### ISSUE TITLE
repl not working?

### ISSUE THREAD

**Issue by Modog500000** [MikeDev101/cloudlink#21]
For some reason this code(on repl):
`from cloudlink import CloudLink
import time

if __name__ == "__main__":
    cl = CloudLink() # Instanciate the module
    try:
        cl.host(8080, '0.0.0.0') # Start the module in server mode, host on port 3000
        
        while cl.mode == 1: # Some other spaghetti code to keep the script running while the connection is live
            time.sleep(0.1)
        
    except KeyboardInterrupt:
        cl.stop() # Stops the server and exits`

Does not work and gives me this error:

----------------------------------------
Exception happened during processing of request from ('172.18.0.1', 53214)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 229, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 240, in handle
    self.handshake()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket_server/websocket_server.py", line 391, in handshake
    assert headers['upgrade'].lower() == 'websocket'
KeyError: 'upgrade'
----------------------------------------
ps this project is great and if I get this fixed im probably gonna make a short tutorial for repl to help other people with this

**Comment by Modog500000** [comment]
I figured it out ill be making a tutorial on this at a later late probably withen the next month

**Comment by satyrnsstuff** [comment]
How did you fix this?

**Comment by Ganheso** [comment]
how did you fix this

**Comment by Modog500000** [comment]
Sorry I fixed this with this code on repl:

**Comment by Modog500000** [comment]
OK it wont let me add it as code for some reason properly

**Comment by Modog500000** [comment]
Use the example server but replace the cl.server part with this
`cl.server(port= 8080, ip= "0.0.0.0")`

**Comment by Modog500000** [comment]
and you have to use wss://repl.com/linkgoeshere
