### ISSUE TITLE
CloudLink doesn't load on TurboWarp Desktop on Debian 11

### ISSUE THREAD

**Issue by Mwalters75** [MikeDev101/cloudlink#37]
It was working on normal TurboWarp...
## TurboWarp Desktop
![image](https://user-images.githubusercontent.com/67456566/152166448-3f12440a-75b2-4df1-b529-9a1763a12048.png)
## TurboWarp
![image](https://user-images.githubusercontent.com/67456566/152167707-a8bdac72-17cd-49e0-8e36-05132fbd3ffb.png)

**Comment by MikeDev101** [comment]
Turbowarp Desktop doesn't support Websockets, for some reason.
