### ISSUE TITLE
I can't set my username on repl.

### ISSUE THREAD

**Issue by TermOfficial** [MikeDev101/cloudlink#39]
I can connect, and the client recieves the IP, but when I use the set username block, it just fails.

**Comment by TermOfficial** [comment]
![image](https://user-images.githubusercontent.com/79934414/152567540-478b1d89-ac48-448b-aa52-3d1c24960815.png)
 Here's the image of the console.

**Comment by showierdata9978** [comment]
Because He has not merged my pull request

**Comment by showierdata9978** [comment]
https://github.com/MikeDev101/cloudlink/pull/33

**Comment by MikeDev101** [comment]
merged

**Comment by TermOfficial** [comment]
Now getting to a E:119 | IP Blocked while trying to configure Trusted Access.
I entered in the correct JSON with the send block, but it's not working.

**Comment by TermOfficial** [comment]
Nevermind.

**Comment by TermOfficial** [comment]
Also yes, the merge Mikedev did worked.

**Comment by TermOfficial** [comment]
Nevermind. I'm now getting a E:104 Internal upon trusted access and setting username.

**Comment by TermOfficial** [comment]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/79934414/152664031-a0d76e52-38cd-4241-97a9-43bbc9a6b0d0.png">

**Comment by TermOfficial** [comment]
Fixed by using meower's cloudlink.py
