### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by MikeDev101** [MikeDev101/cloudlink#6]
I'm creating this thread so anyone with problems connecting can give me some insight so I can help fix it. I don't know what's the problem, but if anyone has a issue, feel free to report it here.

**Comment by hf3i05** [comment]
Hey @MikeDev101 ,
I am still having problems with CloudLink. I don't why it is, but just in case, here are my device details:

> 

- OS: Windows 10 Home Premium
- Browser: [Opera](https://www.opera.com) (stable build)

**Comment by MikeDev101** [comment]
> Hey @MikeDev101 ,
> I am still having problems with CloudLink. I don't why it is, but just in case, here are my device details:
> 
> > 
> 
> - OS: Windows 10 Home Premium
> - Browser: [Opera](https://www.opera.com) (stable build)

I believe there might be an issue with opera. I made CloudLink on Firefox, try that instead and if not send me a msg.

**Comment by hf3i05** [comment]
> > Hey @MikeDev101 ,
> > I am still having problems with CloudLink. I don't why it is, but just in case, here are my device details:
> > > 
> > 
> > 
> > 
> > * OS: Windows 10 Home Premium
> > * Browser: [Opera](https://www.opera.com) (stable build)
> 
> I believe there might be an issue with opera. I made CloudLink on Firefox, try that instead and if not send me a msg.

OK.

**Comment by hf3i05** [comment]
My server web client actually fails to load in Firefox, which means I can't connect to the server.

**Comment by MikeDev101** [comment]
By any chance, do you have any info about how you are connecting to the server? (Reverse proxy, port forward?)

**Comment by DabDatBass** [comment]
Hey @MikeDev101 , 

Still having problems. I can make a script where it repeatedly tries to connect until it **does** connect, and it would act like a forever loop.

It might be I have a Chromebook...

**Comment by MikeDev101** [comment]
@DabDatBass sure, go ahead.

Be advised that you can't run server software on a chromebook.

**Comment by GhostedNotFound** [comment]
> @DabDatBass sure, go ahead.
> 
> Be advised that you can't run server software on a chromebook.

I also have a chromebook but I am trying to run it on a online IDE but it seems to not work still.

It says "Unable to connect to port 8080."

**Comment by MikeDev101** [comment]
> @GhostedNotFound
> > @DabDatBass sure, go ahead.
> > Be advised that you can't run server software on a chromebook.
> 
> I also have a chromebook but I am trying to run it on a online IDE but it seems to not work still.
> 
> It says "Unable to connect to port 8080."

A reverse proxy is needed. I'm not sure how to fix this at this time.

**Comment by DabDatBass** [comment]
it was because i didn't have a server :/ close this

**Comment by MikeDev101** [comment]
that happens when the connection times out. Try pinging the server instead using the ping command.

**Comment by TermOfficial** [comment]
![image](https://user-images.githubusercontent.com/79934414/152667594-4b09b961-cac8-491b-98e5-a535a381d6b2.png)
re-pasted from og issue

**Comment by MikeDev101** [comment]
Converting to discussion.
