### ISSUE TITLE
CL4 packet sending very unoptimized

### ISSUE THREAD

**Issue by tnix100** [MikeDev101/cloudlink#63]
CL4 is very cool, but it has a problem of just being very unoptimized in some places and will struggle at scale (such as in Meower).

Here's some things I noticed about it:
- To send to a room, you have to list all clients online and the room ID (would just be nicer if I could send directly to a whole room with it's ID), this causes it to loop through every client to check if they're in the room instead of storing who's in that room somewhere other than their client object
- To send to a client it has to go through all clients connected and check their ID/username

**Comment by MikeDev101** [comment]
https://github.com/MikeDev101/cloudlink/commit/cb46a776fb0448c4f44a8b09f981b8c2fb2f3e6c

**Comment by MikeDev101** [comment]
https://github.com/MikeDev101/cloudlink/commit/f8ab4e0e4ca8835f1553191a640fe520b6f8a19c

**Comment by MikeDev101** [comment]
https://github.com/MikeDev101/cloudlink/commit/c86e1b9635ae05b0350021b82f2555de990e514e

**Comment by MikeDev101** [comment]
Closing. Should be optimized enough as of 4.0-early3
