### ISSUE TITLE
Internet connection is slow after attempting to use CloudLink

### ISSUE THREAD

**Issue by hf3i05** [MikeDev101/cloudlink#7]
Hello @MikeDev101,
For some reason, my Internet connection has become slower after using CloudLink.
I don't know why, but I have already tried a lot of times to paste `python server.py
pause` into Command Prompt.

**Comment by MikeDev101** [comment]
Hm, I'm not entirely sure about that. I don't know entirely how that should happen, since I can't really replicate an internet problem.

**Comment by hf3i05** [comment]
> Hm, I'm not entirely sure about that. I don't know entirely how that should happen, since I can't really replicate an internet problem.

OK.
