### ISSUE TITLE
Use Type hinting for type checking

### ISSUE THREAD

**Issue by showierdata9978** [MikeDev101/cloudlink#74]
In the current source code you can find snippets of code like this
```py

def function(self, supost_to_be_int):
   if type(supost_to_be_int) is int:
      ...
   else:
     return TypeError
```

when it could be 

```py
def function(self, supost_to_be_int:int) -> ... :
    ...
```

as with type hinting python raises an error for you if it is not the correct type

**Comment by showierdata9978** [comment]
Most Library`s use Type Hinting too

**Comment by MikeDev101** [comment]
Closing for now, because of https://github.com/MikeDev101/cloudlink/commit/e8d3fc400f85b7b4b6057575cfdb4649a7e0e601

Oh and because type hinting doesn't always catch things in JSON
