### ISSUE TITLE
Server and client events/callbacks don't have feature parity

### ISSUE THREAD

**Issue by MikeDev101** [MikeDev101/cloudlink#79]
^

**Comment by showierdata9978** [comment]
one of them is the most important one. on_packet.

**Comment by MikeDev101** [comment]
> one of them is the most important one. on_packet. (client side)

Use custom callbacks instead of listening for all possible requests.

**Comment by showierdata9978** [comment]
> > one of them is the most important one. on_packet. (client side)
> 
> Use custom callbacks instead of listening for all possible requests.

in the specific use case, im printing for debug

**Comment by MikeDev101** [comment]
Closing
