### ISSUE TITLE
CloudLink 4 python server does not function

### ISSUE THREAD

**Issue by hdboye** [MikeDev101/cloudlink#81]
When this code is run:
```
from cloudlink import cloudlink
cl = cloudlink()

cl.server(logs = True)
```
with the cloudlink module installed, it prints 

> CloudLink v0.1.9.1

and then the code stops. Enabling the log parameter in the server function does not log anything.
Is my code wrong, or is this an issue with the server?

Python 3.10.7:6cc6b13
Windows 10 Pro 19044.2251

**Comment by MikeDev101** [comment]
You need to call `cl.server.run` to start.

`cloudlink.server.run(host:str, port:int)`

**Comment by hdboye** [comment]
> You need to call `cl.server.run` to start.
> 
> `cloudlink.server.run(host:str, port:int)`

Changing my cl.server function from
`cl.server(logs = True)` to `cl.server.run("localhost",3000)` just gives me
```
Traceback (most recent call last):
  File "C:\Users\MyPcsName\Downloads\cloudlinktest\main.py", line 4, in <module>
    cl.server.run("localhost",3000)
AttributeError: 'function' object has no attribute 'run'
```

Inspecting the code of the package, i don't see anything referencing this either.
I'm on the latest version of the package from pip.

**Comment by hdboye** [comment]
Figured it out lol, quite a stupid mistake on my end.

It wasn't `cl.server.run()` but instead `cl.server().run()`. That got it to work.
Thanks for the help;

**Comment by MikeDev101** [comment]
My mistake for not clarifying. Glad you figured it out!

As a future reference for anyone curious, you could pass the return of `cl.server()` into a variable, and then call `run()` from that variable.

Example:
```
from cloudlink import cloudlink

cl = cloudlink()

server = cl.server(logs=true)

... # Do something with the server variable, such as custom methods

server.run("127.0.0.1", 3000)
```

Using that `server` variable, you can initialize more functions of the server before starting it. Mainly, custom methods, listeners, or binding events.

**Comment by hdboye** [comment]
I wrote some server and client documentation into the CL4 docs, hope that's okay. It's basic but it should get people started with a simple server they could use for their games.

https://hackmd.io/g6BogABhT6ux1GA2oqaOXA?view#Python-Client
https://hackmd.io/g6BogABhT6ux1GA2oqaOXA?view#Server
