### ISSUE TITLE
issue when hosting cl4 on an nginx-based server

### ISSUE THREAD

**Issue by hdboye** [MikeDev101/cloudlink#84]
I currently have an nginx-based server from DiscordBotHosting with pterodactyl panel, but when i try to enter the ip that it gave me it always returns
`OSError: [Errno 99] error while attempting to bind on address ('the ip', the port): cannot assign requested address`
I know it's not the server's fault because i've hosted tons of things to that ip and port without fail, it's only this..

This is my code:
```
from cloudlink import cloudlink
cl = cloudlink()
cls = cl.server()

cls.run(ip = "insert my servers ip hete", port = insert port here)
```

Am i doing something wrong or is this an issue with the code?

edit: when i use 0.0.0.0 it DOES work, but only on unsecured websocket which is not preferrable

**Comment by MikeDev101** [comment]
I'm honestly not sure. If it's raising an OSError, it's beyond the scope of Cloudlink itself. I suggest you share this with [aaugustin/websockets](https://github.com/aaugustin/websockets) instead since that is what CL4 runs on.

**Comment by hdboye** [comment]
alright then, i'll check that out then
