### ISSUE TITLE
Issues when deploying on railway.app

### ISSUE THREAD

**Issue by TheShovel** [MikeDev101/cloudlink#86]
I try to start the example server and I get this error.

```
Traceback (most recent call last):
File "server_example.py", line 1, in <module>
from cloudlink import cloudlink
File "/app/cloudlink/__init__.py", line 1, in <module>
from .cloudlink import *
File "/app/cloudlink/cloudlink.py", line 1, in <module>
from .supporter import supporter
File "/app/cloudlink/supporter.py", line 166
match validation:
^
SyntaxError: invalid syntax
```

Previously I was using Heroku and it worked fine, but because it became expensive, I am trying to run this on railway.
Any help is appreciated, thank you!

**Comment by showierdata9978** [comment]
cloudlink 4.0 only works on <= python3.10

**Comment by TheShovel** [comment]
Oh ok, thanks, gonna tell it to install a older version of python.

**Comment by MikeDev101** [comment]
> cloudlink 4.0 only works on <= python3.10

Correction: Python >=3.10.

Heroku is untested for support, but try running the server example file. Modify the IP argument to use 0.0.0.0, or listen to all possible IPs on the server.

https://github.com/MikeDev101/cloudlink/blob/master/server_example.py

**Comment by showierdata9978** [comment]
oop, yeah typo

**Comment by TheShovel** [comment]
Ok adding `NIXPACKS_PYTHON_VERSION = 3.10` to environment variables fixes the issue. The ip is already automatic because it works with the herkou setup I had before.
Thanks again for the help :)
