### ISSUE TITLE
no way to send a custom command to a client 

### ISSUE THREAD

**Issue by showierdata9978** [MikeDev101/cloudlink#95]
For #91 im returning a message sent to a client from the home server via the non home server that is a statuscode generated via supporter.generate_statuscode

I cant return it to the original client

**Comment by MikeDev101** [comment]
![ihadastroke](https://user-images.githubusercontent.com/12957745/207421485-8e63fced-e5b2-4be7-939c-6347ebdc4869.png)

**Comment by showierdata9978** [comment]
sry adhd

translated:

For Suite im connected to the home server, from another server. 
Im trying to create a kind of relay for statuscodes.

current code
```py
    async def statuscode(self, message, listener):
        if listener not in self.waiting_clients: return

        client = self.waiting_clients[listener]

        human_ok, machine_ok = self.supporter.generate_statuscode("OK")

        if not (((message["code"] == human_ok) or (message["code_id"] == machine_ok))):
            await 
```

where i only need to handle `OK` for sending a client its username, and setting it on the server

**Comment by showierdata9978** [comment]
maybe i missed a method...

`send_packet_unicast`
