### ISSUE TITLE
connection failed (400 Bad Request)

### ISSUE THREAD

**Issue by PalmarHealer** [MikeDev101/cloudlink#96]
i'm running Cloudlink server v0.1.9.2 on a Ubuntu 20.04 server and everytime i try to Connect with TurboWarp i get this error

```
 [2022-12-16 19:31:54,479 | 1671215514.479958] (140050247173952 - MainThread) INFO: connection failed (400 Bad Request)
 [2022-12-16 19:31:54,480 | 1671215514.480297] (140050247173952 - MainThread) INFO: connection 
```

**Comment by PalmarHealer** [comment]
does anyone know what i can do?

**Comment by showierdata9978** [comment]
are you using wss for localhost?

if you are, then thats why

**Comment by MikeDev101** [comment]
Any time a bad request error is raised, it means you are attempting to connect to the server using the WebSocket Secure (WSS://) protocol. CL only supports the normal WebSocket protocol (WS://).

If you want to access your server using a secure medium, use a reverse proxy or tunnel service. This page has known working examples: https://github.com/MikeDev101/cloudlink/discussions/56

**Comment by MikeDev101** [comment]
However, since the underlying WebSocket library being used has full WSS:// support, I suggest taking a look into enabling secure WebSockets here: https://websockets.readthedocs.io/en/stable/howto/quickstart.html#encrypt-connections

**Comment by showierdata9978** [comment]
> Any time a bad request error is raised, it means you are attempting to connect to the server using the WebSocket Secure (WSS://) protocol. CL only supports the normal WebSocket protocol (WS://).
> 
> If you want to access your server using a secure medium, use a reverse proxy or tunnel service. This page has known working examples: #56

ninga`d ya

**Comment by PalmarHealer** [comment]
> are you using wss for localhost?
> 
> if you are, then thats why

No it is running on a public server and I'm connecting with `wss://46.228.199.189:12749` and the config is this `server.run(ip="46.228.199.189", port=12749)`

**Comment by showierdata9978** [comment]
> > are you using wss for localhost?
> > if you are, then thats why
> 
> No it is running on a public server and I'm connecting with `wss://46.228.199.189:12749` and the config is this `server.run(ip="46.228.199.189", port=12749)`

cloudlink is currently not rated for being connected to directly other then localhost, as it cant connect wss.
it is recomended to use a reverse proxy like cloudflared to make that Security (and make wss work)

**Comment by PalmarHealer** [comment]
I have now taken Ngrok because I already know it, but the problem remains the same. Maybe something is wrong about turbovarp.

And the error message has not even changed

![grafik](https://user-images.githubusercontent.com/93807726/208174015-1d135693-1e10-41ce-adbc-5e4145db5ceb.png)
```
[2022-12-16 20:19:51,023 | 1671218391.023303] (140096250709824 - MainThread) INFO: Cloudlink server v0.1.9.2
[2022-12-16 20:19:51,049 | 1671218391.049408] (140096250709824 - MainThread) INFO: server listening on [::1]:3000
[2022-12-16 20:19:51,049 | 1671218391.049549] (140096250709824 - MainThread) INFO: server listening on 127.0.0.1:3000
[2022-12-16 20:20:38,997 | 1671218438.997592] (140096250709824 - MainThread) INFO: connection failed (400 Bad Request)
[2022-12-16 20:20:38,998 | 1671218438.998022] (140096250709824 - MainThread) INFO: connection closed
```

**Comment by showierdata9978** [comment]
Use wss with reverse proxy's, they handle all of that

**Comment by PalmarHealer** [comment]
I'm stupid than I thought. I started ngrok with
`ngrok tcp 3000`
instead of
`ngrok http 300`
Sorry for all the noise here

> And for those who have the same problem. Just read cleanly what is written there

**Comment by MikeDev101** [comment]
RTM people, lmao.

https://github.com/MikeDev101/cloudlink/discussions/56 says:
> ngrok | ✅ **HTTP mode on port 3000**

or whatever port you are using for the server
