### ISSUE TITLE
Module Object not callable

### ISSUE THREAD

**Issue by David-Orangemoon** [MikeDev101/cloudlink#99]
'module' object is not callable
  File "C:\Users\owner\Desktop\Projects\Extensions\Turbowarp\D7CloudlinkServer.py", line 6, in <module>
    cl = cloudlink() # Instanciate the parent cloudlink object
TypeError: 'module' object is not callable

its just not working

**Comment by showierdata9978** [comment]
thats not the CL class. thats the CL module. the cl class is located at cloudlink.Cloudlink

**Comment by David-Orangemoon** [comment]
Well now server.bindevent() isn't working 'server' object has no attribute 'bind_event'

**Comment by showierdata9978** [comment]
your using cl completely wrong then

https://github.com/MikeDev101/cloudlink/blob/master/server_example.py

**Comment by David-Orangemoon** [comment]
> your using cl completely wrong then
> 
> https://github.com/MikeDev101/cloudlink/blob/master/server_example.py

That is the exact file I am using

**Comment by showierdata9978** [comment]
are you sure you are using cl4?

**Comment by tnix100** [comment]
What cl version do you have?

**Comment by David-Orangemoon** [comment]
> What cl version do you have?

One I just downloaded off of pip.

**Comment by David-Orangemoon** [comment]
> > What cl version do you have?
> 
> One I just downloaded off of pip.

Using the docs of course

**Comment by tnix100** [comment]
Could you try `pip list` and see what version it says for cloudlink?

**Comment by David-Orangemoon** [comment]
> Contributor

0.1.8.4

**Comment by showierdata9978** [comment]
cl is version 0.1.9.1

**Comment by David-Orangemoon** [comment]
> cl is version 0.1.9.1

how do I update?

**Comment by showierdata9978** [comment]
pip install cloudlink --upgrade

**Comment by David-Orangemoon** [comment]
> pip install cloudlink --upgrade

It says its already up to date? Requirement already satisfied: cloudlink in

**Comment by tnix100** [comment]
What about `pip install cloudlink==0.1.9.1`?

**Comment by David-Orangemoon** [comment]
> What about `pip install cloudlink==0.1.9.1`?

`ERROR: Could not find a version that satisfies the requirement cloudlink==0.1.9.1` it doesn't even exist on pip

**Comment by MikeDev101** [comment]
The pip version hasn't been maintained in a while. Please download the latest copy directly from this repo.

**Comment by showierdata9978** [comment]
server is actually borked

**Comment by showierdata9978** [comment]
im testing #91 RN

**Comment by MikeDev101** [comment]
closing since stale
